### ISSUE TITLE
using multiple GPU

### ISSUE THREAD

**Issue by gorgW** [openmm/openmm-plumed#88] opened 2024-07-31 18:35 UTC
When I use multiple gpus for openmm it works normally as expected, also when I use openmm-plumed using 1 gpu it also works normally, but when I add plumed script to openmm with multiple gpus, it just stops and the simulation doesn't run, without giving any error. Is there anything I should add explicitly to plumed to allow for using multiple gpus ? 

Thanks.

**Comment by peastman** [comment] 2024-08-01 21:11
I can reproduce it.  I'm trying to track down the cause, but it's taking a while.  I think there's a deadlock somewhere, but it doesn't seem to be in the places I would have expected.

**Comment by gorgW** [comment] 2024-09-03 23:32
I still couldn't find the cause of the problem, could you ?

**Comment by peastman** [comment] 2024-09-04 20:08
Thanks for reminding me.  I've narrowed it down to [this line](https://github.com/openmm/openmm/blob/5ce6a85d4ed56dd76acbc53e4f3c963cb20fdc1f/platforms/common/src/ComputeContext.cpp#L719).  A worker thread is waiting for another thread to signal it that there's work to do, and not receiving it.  I'm not sure why.  Let me take another look and see if I can figure out the rest of it.

**Comment by peastman** [comment] 2024-09-05 17:51
I think I understand what's going on.  The fix should be fairly easy.

**Comment by peastman** [comment] 2024-09-05 18:59
The fix is in https://github.com/openmm/openmm/pull/4645.

**Closed** 2024-09-05 22:32 UTC
